In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
data = pd.read_csv("Churn_Modelling.csv")

In [4]:
X = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [23]:
ann = tf.keras.models.Sequential()

In [24]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [25]:
ann.add(tf.keras.layers.Dense(units = 6 ,activation = 'relu'))

In [26]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [28]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [37]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 6)

Epoch 1/6
219/219 [==============================] - 0s 962us/step - loss: 0.5146 - accuracy: 0.7997
Epoch 2/6
219/219 [==============================] - 0s 990us/step - loss: 0.4517 - accuracy: 0.8053
Epoch 3/6
219/219 [==============================] - 0s 1ms/step - loss: 0.4317 - accuracy: 0.8171
Epoch 4/6
219/219 [==============================] - 0s 1ms/step - loss: 0.4228 - accuracy: 0.8207
Epoch 5/6
219/219 [==============================] - 0s 766us/step - loss: 0.4173 - accuracy: 0.8210
Epoch 6/6
219/219 [==============================] - 0s 1ms/step - loss: 0.4125 - accuracy: 0.8237


In [38]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [39]:
y_predict = ann.predict(X_test)
y_predict = (y_predict > 0.5)
print(np.concatenate((y_predict.reshape(len(y_predict), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predict)
print(cm)
accuracy_score(y_test, y_predict)

[[2298   81]
 [ 431  190]]


0.8293333333333334